env: CarRacing-v2
gamma: 0.99
tau: 0.005
buffer_size: 10000
actor_lr: 0.0001
critic_lr: 0.001

dataset:
  val_split: 0.1

cnn_model:
  in_channels: 3
  out_channels: [32, 64, 128]
  kernel_sizes: 3
  stride: 1
  paddings: 1

training:
  batch_size: 64
  epoch: 100
  max_steps_per_episode: 100
  patience: 10
  et_patience: 5
  min_delta: 0.001
  save_path: ./checkpoints/ddpg_model.pth
