# config/env.yaml
env_name: CarRacing-v3
seed: 42

gamma: 0.99
tau: 0.005
buffer_size: 50000
actor_lr: 0.0001
critic_lr: 0.001

dataset:
  val_split: 0.1

cnn_model:
  in_channels: 3
  out_channels: [32, 64, 128]
  kernel_sizes: [3, 3, 3]
  stride: 2
  paddings: 1

training:
  batch_size: 64
  episodes: 500 
  max_steps_per_episode: 500
  patience: 20
  save_path: ./ddpg/checkpoints/best_actor.pth